server:
  servlet:
    contextPath: /insights-api
  port: 8625

spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      connection-timeout: 60000
      validation-timeout: 1000
      maximum-pool-size: 10
  jdbc:
    template:
      query-timeout: 300
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml

graphql:
  servlet:
    corsEnabled: false
    async-timeout: 300000

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info