sentry.dsn=https://106afbb6902471d43116fb5625509bf2@o4506354031329280.ingest.sentry.io/4506354044502016
# Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0
sentry.debug=true
sentry.logging.enabled=true
sentry.logging.minimum-event-level=info
sentry.logging.minimum-breadcrumb-level=debug
